In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [5]:
data = pd.read_csv("ultimate_student_productivity_dataset_5000.csv")
data['pass'] = np.where(data['exam_score'] >= 24, 1, 0)
X = data.select_dtypes(include=np.number)
X = X.drop(columns=['exam_score','student_id','pass'])
y = data['pass']
print(data['pass'].head())

0    1
1    0
2    0
3    0
4    1
Name: pass, dtype: int64


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt_pred = dt.predict(X_test)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
knn_pred = knn.predict(X_test)

svm = SVC(kernel='linear')
svm.fit(X_train,y_train)
svm_pred = svm.predict(X_test)

print("Decision Tree Accuracy : ",accuracy_score(y_test,dt_pred))
print("Decision Tree Confusion Matrix : \n",confusion_matrix(y_test,dt_pred))
print("\nk-NN Accuracy : ",accuracy_score(y_test,knn_pred))
print("k-NN Confusion Matrix : \n",confusion_matrix(y_test,knn_pred))
print("\nSVM Accuracy : ",accuracy_score(y_test,svm_pred))
print("SVM Confusion Matrix : \n",confusion_matrix(y_test,svm_pred))
print("\nClassification Report (SVM) : \n", classification_report(y_test,svm_pred))

Decision Tree Accuracy :  0.836
Decision Tree Confusion Matrix : 
 [[587  71]
 [ 93 249]]

k-NN Accuracy :  0.853
k-NN Confusion Matrix : 
 [[606  52]
 [ 95 247]]

SVM Accuracy :  0.875
SVM Confusion Matrix : 
 [[606  52]
 [ 73 269]]

Classification Report (SVM) : 
               precision    recall  f1-score   support

           0       0.89      0.92      0.91       658
           1       0.84      0.79      0.81       342

    accuracy                           0.88      1000
   macro avg       0.87      0.85      0.86      1000
weighted avg       0.87      0.88      0.87      1000

